---
title: "Overview of Group Projects"
format: html
---



::: {.grid}


::: {.g-col-2}
**Group ● Purple **<br> 

Members:

- Ying Cui
- Ethel Pruss
- Oliver Eksteins
- T’kara Mullins
- Zeynep M. Suata
:::

::: {.g-col-4}
Topic: Does prior affiliation relate to movement and gaze coordination dynamics in dyadic interaction?<br>
[Github repository](https://github.com/ethelpruss/purplecircle) <br>
:::

::: {.g-col-2}
**Group ■ Blue**<br> 

Members:

- Kristina Koch
- Matteo Schmelzer
- Nthabiseng Shongwe
- Solveigh Janzen
- Tim Murphy
:::

::: {.g-col-4}
Topic: Wobbly friends <br>
[Github repository](https://github.com/matteoschmelzer/wobblyFriends) <br>
:::

::: {.g-col-2}
**Group ▲ Green**<br> 

Members:

- Apollo Reyes Martes
- Lisa Gottschalk
- Hester van Beek
- Sébastien Vandenitte
- Ward Deferm

:::

::: {.g-col-4}
Topic: Impact of postural (in)stability on the temporal coordination of speech and gesture during face-to-face interactions<br>
[Github repository](https://github.com/hestervbeek/BIGS-TilburgSS) <br>
:::

::: {.g-col-2}
**Group ★ Yellow**<br> 

Members:

- Jemima Agnew
- Madalina Sas
- Moritz Bammel
- Satyajeet Prabhu
- Svea Boesch
:::

::: {.g-col-4}
Topic: Exploring the relationships between eyebrow movement, pitch and effects on communication and accuracy in the guessing game <br>
[Github repository](https://github.com/mearlboro/RaisedExpectations)<br>
:::

::: {.g-col-2}
**Group ◆ Orange**<br> 

Members:

- Michal Weiss
- Tessa Cancio Pastor
- Timo Kalliokoski
- Xuancu Hong
- Ann Hogenhuis
:::

::: {.g-col-4}
Topic: <br>
Repository: <br>
:::

::: {.g-col-2}
**Group ✚ Pink**<br>

Members:

- Kyle Samson
- Mariana Carneiro de Andrade
- Ngoungouo Yiagnigni Abass
- Teona Banu
- Thibaud Glasman
- Tobias Ashdown
:::

::: {.g-col-4}
Topic: Multimodal variability as a predictor of social judgment <br>
[Github repository](https://github.com/MCarneirodeAndrade/pinkcross) <br>
:::

:::

